# Generated by Django 3.1.4 on 2020-12-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personne', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=254, null=True)),
                ('popularite', models.TextField(blank=True, null=True)),
                ('personnage', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'acteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categ', models.IntegerField()),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personne', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=254, null=True)),
                ('popularite', models.TextField(blank=True, null=True)),
                ('departement', models.CharField(blank=True, max_length=254, null=True)),
                ('job', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'equipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personne', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=254, null=True)),
                ('popularite', models.TextField(blank=True, null=True)),
                ('departement', models.CharField(blank=True, max_length=254, null=True)),
                ('job', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'equipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmActeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_acteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmEquipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_equipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmProductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField()),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=254, null=True)),
                ('poster', models.CharField(blank=True, max_length=254, null=True)),
                ('plot', models.CharField(blank=True, max_length=254, null=True)),
                ('vo', models.CharField(blank=True, max_length=254, null=True)),
                ('duree', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_production', models.IntegerField()),
                ('logo', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'productions',
                'managed': False,
            },
        ),
    ]
