# Generated by Django 3.1.4 on 2021-01-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteurs',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=254, null=True)),
                ('popularite', models.FloatField(blank=True, null=True)),
                ('personnage', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'acteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_categ', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directeurs',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=254, null=True)),
                ('popularite', models.FloatField(blank=True, max_length=254, null=True)),
                ('departement', models.CharField(blank=True, max_length=254, null=True)),
                ('job', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'diecteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmActeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_acteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmDirecteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_directeurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmProductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'film_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id_video', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=254, null=True)),
                ('poster', models.CharField(blank=True, max_length=254, null=True)),
                ('plot', models.CharField(blank=True, max_length=254, null=True)),
                ('vo', models.CharField(blank=True, max_length=254, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plateformes',
            fields=[
                ('id_plateforme', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('logo', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'plateformes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id_production', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saisons',
            fields=[
                ('id_saison', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_episode', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('num_saison', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saisons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieActeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_acteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieDirecteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_directeurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeriePlateformes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_plateformes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieProductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_video', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=254, null=True)),
                ('poster', models.CharField(blank=True, max_length=254, null=True)),
                ('plot', models.CharField(blank=True, max_length=254, null=True)),
                ('vo', models.CharField(blank=True, max_length=254, null=True)),
                ('nb_saison', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('note', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_films',
            },
        ),
        migrations.CreateModel(
            name='RatingSaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True)),
                ('saison', models.ForeignKey(db_column='id_saison', on_delete=django.db.models.deletion.DO_NOTHING, to='TheApi.saisons')),
            ],
            options={
                'db_table': 'rating_series',
            },
        ),
    ]
