# Generated by Django 3.1.4 on 2020-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_films',
                'managed': False,
            },
        ),
    ]
