# Generated by Django 3.1.4 on 2021-01-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TheApi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsaison',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingfilms',
            name='film',
            field=models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='TheApi.films'),
        ),
        migrations.AddField(
            model_name='ratingfilms',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsaison',
            unique_together={('saison', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingfilms',
            unique_together={('film', 'user')},
        ),
    ]
