# Generated by Django 3.1.4 on 2021-01-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0002_auto_20210101_0252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directeurs',
            table='directeurs',
        ),
    ]
