# Generated by Django 3.1.4 on 2020-12-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0002_auto_20201213_1953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ScoreFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApi.films')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApi.score')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='film',
        ),
    ]
