# Generated by Django 3.1.4 on 2020-12-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0002_ratingfilms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingfilms',
            options={},
        ),
    ]
