# Generated by Django 3.1.4 on 2020-12-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0003_auto_20201221_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingfilms',
            options={'managed': False},
        ),
    ]
