# Generated by Django 3.1.4 on 2020-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0003_auto_20201213_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorefilm',
            unique_together={('score', 'film')},
        ),
    ]
