# Generated by Django 3.1.4 on 2020-12-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheApi', '0004_auto_20201221_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True)),
                ('saison', models.ForeignKey(db_column='id_saison', on_delete=django.db.models.deletion.DO_NOTHING, to='TheApi.saisons')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_series',
                'unique_together': {('saison', 'user')},
            },
        ),
    ]
