# Generated by Django 3.1.4 on 2020-12-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0005_auto_20201213_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateformes',
            fields=[
                ('id_plateforme', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('logo', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'plateformes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saisons',
            fields=[
                ('id_saison', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_episode', models.CharField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('num_saison', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'saisons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeriePlateformes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_plateformes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieProductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serie_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_video', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=254, null=True)),
                ('date_sortie', models.CharField(blank=True, max_length=254, null=True)),
                ('poster', models.CharField(blank=True, max_length=254, null=True)),
                ('plot', models.CharField(blank=True, max_length=254, null=True)),
                ('vo', models.CharField(blank=True, max_length=254, null=True)),
                ('nb_saison', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
    ]
