# Generated by Django 3.1.4 on 2020-12-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0006_filmfavoris'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmFavoris',
        ),
    ]
