# Generated by Django 3.1.4 on 2020-12-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0007_delete_filmfavoris'),
        ('authenticate', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFavoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='TheApi.films')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
