# Generated by Django 3.1.4 on 2020-12-30 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0007_delete_filmfavoris'),
        ('authenticate', '0003_auto_20201230_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmfavoris',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SerieFavoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('serie', models.ForeignKey(db_column='id_serie', on_delete=django.db.models.deletion.DO_NOTHING, to='TheApi.series')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
