# Generated by Django 3.1.4 on 2020-12-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApi', '0007_delete_filmfavoris'),
        ('authenticate', '0004_auto_20201230_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmfavoris',
            options={'verbose_name_plural': 'Films Favoris'},
        ),
        migrations.AlterUniqueTogether(
            name='filmfavoris',
            unique_together={('user', 'film')},
        ),
        migrations.AlterUniqueTogether(
            name='seriefavoris',
            unique_together={('user', 'serie')},
        ),
    ]
